package com.zhao.ssm.bean;

public class Post {

    public Post() {
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    public void setPsource(String psource) {
        this.psource = psource;
    }

    public void setPcontent(String pcontent) {
        this.pcontent = pcontent;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.pid
     *
     * @mbggenerated
     */

    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.psource
     *
     * @mbggenerated
     */
    private String psource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.pcontent
     *
     * @mbggenerated
     */
    private String pcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    public Post(Integer pid, String psource, String pcontent) {
        this.pid = pid;
        this.psource = psource;
        this.pcontent = pcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.pid
     *
     * @return the value of post.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.psource
     *
     * @return the value of post.psource
     *
     * @mbggenerated
     */
    public String getPsource() {
        return psource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.pcontent
     *
     * @return the value of post.pcontent
     *
     * @mbggenerated
     */
    public String getPcontent() {
        return pcontent;
    }
}