package com.zhao.ssm.bean;

public class Sort {
    public Sort() {
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public void setItem1(String item1) {
        this.item1 = item1;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.item1
     *
     * @mbggenerated
     */
    private String item1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbggenerated
     */
    public Sort(Integer id, String name, String info, String item1) {
        this.id = id;
        this.name = name;
        this.info = info;
        this.item1 = item1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.id
     *
     * @return the value of sort.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.name
     *
     * @return the value of sort.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.info
     *
     * @return the value of sort.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.item1
     *
     * @return the value of sort.item1
     *
     * @mbggenerated
     */
    public String getItem1() {
        return item1;
    }
}